In [2]:
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, plot_confusion_matrix
mtest=pd.read_csv(r"C:\\Users\\Nexas\\Northeastern\mnist_test.csv")
mtrain=pd.read_csv(r"C:\\Users\\Nexas\\Northeastern\mnist_train.csv")

In [3]:
mtest.head()


7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
mtrain.head()

5  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.608  0.609  0.610  \
0  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.611  0.612  0.613  0.614  0.615  0.616  0.617  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [5]:
mtest = mtest.to_numpy()
mtrain = mtrain.to_numpy()

In [6]:
mtest[:, 0:1].flatten()

array([2, 1, 0, ..., 4, 5, 6], dtype=int64)

In [7]:
mtest[:,1:785]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [5]:
mtrain[:,0:1].flatten()

array([0, 4, 1, ..., 5, 6, 8], dtype=int64)

In [6]:
mtrain[:,1:785]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [7]:
x_mtest = mtest[:,1:785]
y_mtest = mtest[:, 0:1]
x_mtrain = mtrain[:,1:785]
y_mtrain = mtrain[:,0:1]

In [8]:
#mtrain relabel
y_mtrain0 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain0)):
    y_mtrain0[i] = 1 if y_mtrain[i] == 0 else 0

In [9]:
y_mtrain0[0:100]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [10]:
y_mtrain1 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain1)):
    y_mtrain1[i] = 1 if y_mtrain[i] == 1 else 0

In [11]:
y_mtrain1[0:100]

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [12]:
y_mtrain2 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain2)):
    y_mtrain2[i] = 1 if y_mtrain[i] == 2 else 0

In [13]:
y_mtrain2[0:100]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
y_mtrain3 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain3)):
    y_mtrain3[i] = 1 if y_mtrain[i] == 3 else 0

In [15]:
y_mtrain4 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain4)):
    y_mtrain4[i] = 1 if y_mtrain[i] == 4 else 0

In [16]:
y_mtrain5 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain5)):
    y_mtrain5[i] = 1 if y_mtrain[i] == 5 else 0

In [17]:
y_mtrain6 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain6)):
    y_mtrain6[i] = 1 if y_mtrain[i] == 6 else 0

In [18]:
y_mtrain7 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain7)):
    y_mtrain7[i] = 1 if y_mtrain[i] == 7 else 0

In [19]:
y_mtrain8 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain8)):
    y_mtrain8[i] = 1 if y_mtrain[i] == 8 else 0

In [20]:
y_mtrain9 = np.empty(len(y_mtrain)).astype(int)
for i in range(len(y_mtrain9)):
    y_mtrain9[i] = 1 if y_mtrain[i] == 9 else 0

In [21]:
#mtest relabel
y_mtest0 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest0)):
    y_mtest0[i] = 1 if y_mtest[i] == 0 else 0

In [22]:
y_mtest1 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest1)):
    y_mtest1[i] = 1 if y_mtest[i] == 1 else 0

In [23]:
y_mtest2 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest2)):
    y_mtest2[i] = 1 if y_mtest[i] == 2 else 0

In [24]:
y_mtest3 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest3)):
    y_mtest3[i] = 1 if y_mtest[i] == 3 else 0

In [25]:
y_mtest4 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest4)):
    y_mtest4[i] = 1 if y_mtest[i] == 4 else 0

In [26]:
y_mtest5 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest5)):
    y_mtest5[i] = 1 if y_mtest[i] == 5 else 0

In [27]:
y_mtest6 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest6)):
    y_mtest6[i] = 1 if y_mtest[i] == 6 else 0

In [28]:
y_mtest7 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest7)):
    y_mtest7[i] = 1 if y_mtest[i] == 7 else 0

In [29]:
y_mtest8 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest8)):
    y_mtest8[i] = 1 if y_mtest[i] == 8 else 0

In [30]:
y_mtest9 = np.empty(len(y_mtest)).astype(int)
for i in range(len(y_mtest9)):
    y_mtest9[i] = 1 if y_mtest[i] == 9 else 0

In [32]:
test0 = LogisticRegression(random_state=0, solver='liblinear')

In [33]:
test0.fit(x_mtest, y_mtest0)

LogisticRegression(random_state=0, solver='liblinear')

In [156]:
#Logistic Regression Test Set

In [268]:
test0 = LogisticRegression().fit(x_mtrain, y_mtrain0)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [273]:
test1 = LogisticRegression().fit(x_mtrain, y_mtrain1)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [274]:
test2 = LogisticRegression().fit(x_mtrain, y_mtrain2)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [275]:
test3 = LogisticRegression().fit(x_mtrain, y_mtrain3)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [276]:
test4 = LogisticRegression().fit(x_mtrain, y_mtrain4)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [277]:
test5 = LogisticRegression().fit(x_mtrain, y_mtrain5)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [278]:
test6 = LogisticRegression().fit(x_mtrain, y_mtrain6)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [279]:
test7= LogisticRegression().fit(x_mtrain, y_mtrain7)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [280]:
test8 = LogisticRegression().fit(x_mtrain, y_mtrain8)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [281]:
test9 = LogisticRegression().fit(x_mtrain, y_mtrain9)

X:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#Logistic Regression Train Set

In [50]:
train0 = LogisticRegression(random_state=0, solver='liblinear').fit(x_mtrain, y_mtrain0)

In [51]:
train1 = LogisticRegression(random_state=0, solver='liblinear').fit(x_mtrain, y_mtrain1)

In [52]:
train2 = LogisticRegression(random_state=0, solver='liblinear').fit(x_mtrain, y_mtrain2)

In [60]:
train3 = LogisticRegression(random_state=0, solver='liblinear', max_iter=1000).fit(x_mtrain, y_mtrain3)

In [54]:
train4 = LogisticRegression(random_state=0, solver='liblinear').fit(x_mtrain, y_mtrain4)

In [55]:
train5 = LogisticRegression(random_state=0, solver='liblinear').fit(x_mtrain, y_mtrain5)

In [61]:
train6 = LogisticRegression(random_state=0, solver='liblinear', max_iter=1000).fit(x_mtrain, y_mtrain6)

In [57]:
train7 = LogisticRegression(random_state=0, solver='liblinear').fit(x_mtrain, y_mtrain7)

In [62]:
train8 = LogisticRegression(random_state=0, solver='liblinear', max_iter=1000).fit(x_mtrain, y_mtrain8)

In [63]:
train9 = LogisticRegression(random_state=0, solver='liblinear', max_iter=1000).fit(x_mtrain, y_mtrain9)

In [282]:
#Prediction for test set
test0_pred = test0.predict(x_mtest)

In [283]:
test0_pred

array([0, 0, 1, ..., 0, 0, 0])

In [284]:
test1_pred = test1.predict(x_mtest)

In [285]:
test2_pred = test2.predict(x_mtest)

In [286]:
test3_pred = test3.predict(x_mtest)

In [287]:
test4_pred = test4.predict(x_mtest)

In [288]:
test5_pred = test5.predict(x_mtest)

In [289]:
test6_pred = test6.predict(x_mtest)

In [290]:
test7_pred = test7.predict(x_mtest)

In [291]:
test8_pred = test8.predict(x_mtest)

In [292]:
test9_pred = test9.predict(x_mtest)

In [293]:
#Probability
prob0 = test0.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [294]:
prob1 = test1.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [295]:
prob2 = test2.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [296]:
prob3 = test3.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [297]:
prob4 = test4.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [298]:
prob5 = test5.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [299]:
prob6 = test6.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [300]:
prob7 = test7.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [301]:
prob8 = test8.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [302]:
prob9 = test9.predict_proba(x_mtest[0].reshape(1,-1))[0][1]

In [303]:
#Softmax
sp = [prob0, prob1, prob2, prob3, prob4, prob5, prob6, prob7, prob8, prob9]

In [304]:
np.exp(prob0) / np.sum(np.exp(sp))

0.08499055359093462

In [305]:
np.exp(prob1) / np.sum(np.exp(sp))

0.08498885331491111

In [306]:
np.exp(prob2) / np.sum(np.exp(sp))

0.23048970298916668

In [307]:
np.exp(prob3) / np.sum(np.exp(sp))

0.08508832883563695

In [308]:
np.exp(prob4) / np.sum(np.exp(sp))

0.08498885259667344

In [309]:
np.exp(prob5) / np.sum(np.exp(sp))

0.08855229830610449

In [310]:
np.exp(prob6) / np.sum(np.exp(sp))

0.08593408606446745

In [311]:
np.exp(prob7) / np.sum(np.exp(sp))

0.08498885259667326

In [312]:
np.exp(prob8) / np.sum(np.exp(sp))

0.0849896191087553

In [313]:
np.exp(prob9) / np.sum(np.exp(sp))

0.08498885259667668

In [314]:
y_mtest[0]

array([2], dtype=int64)

In [315]:
#Confusion Matrix
predict0 = test0.predict(x_mtest)
predict1 = test1.predict(x_mtest)
predict2 = test2.predict(x_mtest)
predict3 = test3.predict(x_mtest)
predict4 = test4.predict(x_mtest)
predict5 = test5.predict(x_mtest)
predict6 = test6.predict(x_mtest)
predict7 = test7.predict(x_mtest)
predict8 = test8.predict(x_mtest)
predict9 = test9.predict(x_mtest)

In [316]:
cm0 = confusion_matrix(y_mtest0, predict0)

In [317]:
cm1 = confusion_matrix(y_mtest1, predict1)
cm2 = confusion_matrix(y_mtest2, predict2)
cm3 = confusion_matrix(y_mtest3, predict3)
cm4 = confusion_matrix(y_mtest4, predict4)
cm5 = confusion_matrix(y_mtest5, predict5)
cm6 = confusion_matrix(y_mtest6, predict6)
cm7 = confusion_matrix(y_mtest7, predict7)
cm8 = confusion_matrix(y_mtest8, predict8)
cm9 = confusion_matrix(y_mtest9, predict9)

In [318]:
cm0

array([[8972,   47],
       [  30,  950]], dtype=int64)

In [319]:
cm1

array([[8824,   40],
       [  27, 1108]], dtype=int64)

In [320]:
cm = [cm0,cm1,cm2,cm3,cm4,cm5,cm6,cm7,cm8,cm9]

In [321]:
cm

[array([[8972,   47],
        [  30,  950]], dtype=int64),
 array([[8824,   40],
        [  27, 1108]], dtype=int64),
 array([[8913,   54],
        [ 144,  888]], dtype=int64),
 array([[8887,  102],
        [ 138,  872]], dtype=int64),
 array([[8939,   78],
        [  90,  892]], dtype=int64),
 array([[9033,   74],
        [ 147,  745]], dtype=int64),
 array([[8972,   69],
        [  82,  876]], dtype=int64),
 array([[8898,   74],
        [  96,  931]], dtype=int64),
 array([[8810,  215],
        [ 317,  657]], dtype=int64),
 array([[8822,  168],
        [ 205,  804]], dtype=int64)]

In [344]:
accuracy0= round(test0.score(x_mtest,y_mtest0), 4)
accuracy1= round(test1.score(x_mtest,y_mtest1), 4)
accuracy2= round(test2.score(x_mtest,y_mtest2), 4)
accuracy3= round(test3.score(x_mtest,y_mtest3), 4)
accuracy4= round(test4.score(x_mtest,y_mtest4), 4)
accuracy5= round(test5.score(x_mtest,y_mtest5), 4)
accuracy6= round(test6.score(x_mtest,y_mtest6), 4)
accuracy7= round(test7.score(x_mtest,y_mtest7), 4)
accuracy8= round(test8.score(x_mtest,y_mtest8), 4)
accuracy9= round(test9.score(x_mtest,y_mtest9), 4)

In [350]:
accuracy = [accuracy0,accuracy1,accuracy2,accuracy3,accuracy4,accuracy5,accuracy6,accuracy7,accuracy8,accuracy9]

In [352]:
accuracy

[0.9923, 0.9933, 0.9802, 0.976, 0.9832, 0.9779, 0.9849, 0.983, 0.9468, 0.9627]

In [369]:
print(cm)

[array([[8972,   47],
       [  30,  950]], dtype=int64), array([[8824,   40],
       [  27, 1108]], dtype=int64), array([[8913,   54],
       [ 144,  888]], dtype=int64), array([[8887,  102],
       [ 138,  872]], dtype=int64), array([[8939,   78],
       [  90,  892]], dtype=int64), array([[9033,   74],
       [ 147,  745]], dtype=int64), array([[8972,   69],
       [  82,  876]], dtype=int64), array([[8898,   74],
       [  96,  931]], dtype=int64), array([[8810,  215],
       [ 317,  657]], dtype=int64), array([[8822,  168],
       [ 205,  804]], dtype=int64)]
